### login
POST {{baseUri}}/auth/login
Content-Type: application/json

{
  "username": "GaspardDePorto",
  "password": "gaspardLeLeopard",
  "rememberMe": true
}
> {%
client.global.set("access", response.body.access_token);
client.global.set("refresh", response.body.refresh_token);
%}

### Refresh token
GET {{baseUri}}/auth/refreshToken
Authorization: {{refresh}}

> {%
client.global.set("access", response.body.access_token);
%}


### Get user by his token
POST {{baseUri}}/auth/getuserbytoken
Authorization: {{refresh}}