### login valid
POST {{baseUri}}/auth/login
Content-Type: application/json

{
  "username": "bazz",
  "password": "Mdpuser.1",
  "rememberMe": true
}
> {%
client.global.set("token", response.body.access_token);
%}

### GET an object
GET {{baseUri}}/object/2
Authorization: {{token}}


### GET an object
GET {{baseUri}}/object/member/1
Authorization: {{token}}

### Make an object
POST {{baseUri}}/object
Content-Type: application/json
Authorization: {{token}}

{
  "type": {
    "idType": 4
  },
  "description": "test",
  "status": "available",
  "image": null,
  "idOfferor": 1
}

### update an object
PUT {{baseUri}}/object/update
Content-Type: application/json
Authorization: {{token}}

{
  "idObject": 2,
  "type": {
    "idType": 3
  },
  "description": "Cadre représentant un chien noir sur un fond noir.",
  "status": "available",
  "idOfferor": 3
}