### login valid
POST {{baseUri}}/auth/login
Content-Type: application/json

{
  "username": "bri",
  "password": "Rad;293",
  "rememberMe": true
}
> {%
client.global.set("token", response.body.access_token);
%}


### login valid bazz
POST {{baseUri}}/auth/login
Content-Type: application/json

{
  "username": "bazz",
  "password": "Mdpuser.1",
  "rememberMe": true
}
> {%
client.global.set("token", response.body.access_token);
%}

### GET an object
GET {{baseUri}}/object/30
Authorization: {{token}}


### GET an object
GET {{baseUri}}/object/member/10
Authorization: {{token}}

### Make an object with his offer
POST {{baseUri}}/object
Content-Type: application/json
Authorization: {{token}}

{
  "timeSlot": "time slot test",
  "object": {
    "type": {
      "idType": 0,
      "typeName": "Croissant"
    },
    "description": "C'est une voiture de fortnite",
    "image": null
  }
}

### update an object
PUT {{baseUri}}/object/update
Content-Type: application/json
Authorization: {{token}}

{
  "idObject": 2,
  "type": {
    "idType": 3
  },
  "description": "Cadre représentant un chien noir sur un fond noir.",
  "status": "available",
  "idOfferor": 3
}


### cancel object
POST {{baseUri}}/object/cancel
Content-Type: application/json
Authorization: {{token}}

{
  "idObject": 2
}

### give object
POST {{baseUri}}/object/give
Content-Type: application/json
Authorization: {{token}}

{
  "idObject": 5
}

### mark object to not collected
POST {{baseUri}}/object/notCollected
Content-Type: application/json
Authorization: {{token}}

{
  "idObject": 5
}


