### disconnect
GET {{baseUri}}/falseroute
Content-Type: application/json

> {%
client.global.clearAll()
%}

### login valid
POST {{baseUri}}/auth/login
Content-Type: application/json

{
  "username": "AlbertDeBucarest",
  "password": "albertLePoulet",
  "rememberMe": true
}
> {%
client.global.set("access", response.body.access_token);
client.global.set("refresh", response.body.refresh_token);
%}

###
GET {{baseUri}}/offers?search-pattern=bu&self=false
Authorization: {{refresh}}


### GET type object
GET {{baseUri}}/offers?self=false&type=Décoration
Authorization: {{refresh}}

### GET object by status
GET {{baseUri}}/offers?status=
Authorization: {{refresh}}
###
GET {{baseUri}}/offers/lasts

###
POST {{baseUri}}/offers/
Authorization: {{refresh}}
Content-Type: application/json

{
  "timeSlot": "time slot test",
  "object": {
    "idObject": 1
  }
}

###
POST {{baseUri}}/offers/
Authorization: {{refresh}}
Content-Type: application/json

{
  "timeSlot": "tous les mois de janvier",
  "object": {
    "type": {
      "idType": 0,
      "typeName": "Croissant"
    },
    "description": "C'est un croissant rien de plus",
    "status": "available",
    "image": null,
    "idOfferor": 2
  }
}

### Get offer by id
GET {{baseUri}}/offers/getById/1
Authorization: {{refresh}}

### Update time slot of a offer
POST {{baseUri}}/offers/update
Authorization: {{refresh}}
Content-Type: application/json

{
  "idOffer": 1,
  "timeSlot": "Je suis disponible le mardi soir",
  "object": {
    "description": "Une fusée tintin",
    "image": null,
    "status": "interested",
    "type": {
      "idType": 4
    }
  }
}

### get all offer
GET {{baseUri}}/offers?search-pattern=samEdi&self=true
Authorization: {{refresh}}

###
PUT {{baseUri}}/offers/
Authorization: {{refresh}}
Content-Type: application/json

{
  "idOffer": 1,
  "timeSlot": "tous les mois de janvier",
  "object": {
    "type": {
      "typeName": "Croissant"
    },
    "description": "C'est un croissant rien de plus",
    "status": "available",
    "image": null,
    "idOfferor": 2
  }
}

###
PUT {{baseUri}}/offers/
Authorization: {{refresh}}
Content-Type: application/json

{
  "idOffer": 1,
  "timeSlot": "en fevrier",
  "object": {
    "type": {
      "typeName": "Canette"
    },
    "description": "C'est une canette rien de plus",
    "status": "available",
    "image": null
  }
}
