### disconnect
GET {{baseUri}}/falseroute
Content-Type: application/json

> {%
client.global.clearAll()
%}

### login valid
POST {{baseUri}}/auth/login
Content-Type: application/json

{
  "username": "bazz",
  "password": "Mdpuser.1",
  "rememberMe": true
}
> {%
client.global.set("access", response.body.access_token);
client.global.set("refresh", response.body.refresh_token);
%}

###
GET {{baseUri}}/offers?search-pattern=bu&self=false
Authorization: {{refresh}}


### GET type object
GET {{baseUri}}/offers?self=false&type=Décoration
Authorization: {{refresh}}

### GET object by status
GET {{baseUri}}/offers?status=assigned
Authorization: {{refresh}}
###
GET {{baseUri}}/offers/lasts

###
POST {{baseUri}}/offers/
Authorization: {{refresh}}
Content-Type: application/json

{
  "timeSlot": "time slot test",
  "object": {
    "idObject": 1
  }
}

###
POST {{baseUri}}/offers/
Authorization: {{refresh}}
Content-Type: application/json

{
  "timeSlot": "tous les mois de janvier",
  "object": {
    "type": {
      "idType": 0,
      "typeName": "Croissant"
    },
    "description": "C'est un croissant rien de plus",
    "status": "available",
    "image": null,
    "idOfferor": 2
  }
}

### Get offer by id
GET {{baseUri}}/offers/getById/11
Authorization: {{refresh}}

### get all offer
GET {{baseUri}}/offers?search-pattern=samEdi&self=true
Authorization: {{refresh}}

###
PUT {{baseUri}}/offers/
Authorization: {{refresh}}
Content-Type: application/json

{
  "idOffer": 7,
  "timeSlot": "uoi",
  "status": "available",
  "object": {
    "type": {
      "typeName": "Vélo, trottinette"
    },
    "description": "je suis une offre",
    "status": "inconnu",
    "image": null,
    "idOfferor": 4
  }
}

###
PUT {{baseUri}}/offers/
Authorization: {{refresh}}
Content-Type: application/json

{
  "idOffer": 1,
  "timeSlot": "en fevrier",
  "object": {
    "type": {
      "typeName": "Canette"
    },
    "description": "C'est une canette rien de plus",
    "status": "available",
    "image": null
  }
}

### Search given member
GET {{baseUri}}/offers/givenOffers/2
Authorization: {{access}}

### Cancel offer
POST {{baseUri}}/offers/cancelOffer
Authorization: {{access}}
Content-Type: application/json

{
  "idOffer": 5
}

### Mark offer to not collected
POST {{baseUri}}/offers/notCollected
Authorization: {{access}}
Content-Type: application/json

{
  "idOffer": 9
}