### login valid
POST {{baseUri}}/auth/login
Content-Type: application/json

{
  "username": "bazz",
  "password": "Mdpuser.1",
  "rememberMe": true
}
> {%
client.global.set("access", response.body.access_token);
client.global.set("refresh", response.body.refresh_token);
%}

###
GET {{baseUri}}/ratings/4
Authorization: {{refresh}}


###
POST {{baseUri}}/ratings/
Authorization: {{refresh}}
Content-Type: application/json

{
  "rating": 2,
  "comment": "bon objet",
  "idObject": 20
}