### login valid
POST {{baseUri}}/auth/login
Content-Type: application/json

{
  "username": "AlbertDeBucarest",
  "password": "albertLePoulet",
  "rememberMe": true
}
> {%
client.global.set("access", response.body.access_token);
client.global.set("refresh", response.body.refresh_token);
%}


###
GET {{baseUri}}/type/id/1
Authorization: {{refresh}}

###
GET {{baseUri}}/type/type_name/Jouets
Authorization: {{refresh}}

###
GET {{baseUri}}/type/allDefault
Authorization: {{refresh}}